on:
  push:
    branches: [master]
    tags:
      - '\d+\.\d+\.\d+' # Triggers on tags like v1.0.0
  pull_request:
    branches: all

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install NSIS
        id: nsis
        uses: negrutiu/nsis-install@v2
        with:
          distro: official

      - name: Show NSIS info
        run: |
          echo "NSIS dir: ${{ steps.nsis.outputs.instdir }}"
          echo "NSIS version: ${{ steps.nsis.outputs.version }}"
          echo "NSIS arch: ${{ steps.nsis.outputs.arch }}"

      - name: Install `NScurl` from GitHub
        uses: negrutiu/nsis-install-plugin@v1
        with:
          github-owner: negrutiu
          github-repo: nsis-nscurl
          github-asset-regex: NScurl\.zip

      - name: Install `AccessControl` from web
        uses: negrutiu/nsis-install-plugin@v1
        with:
          plugin-name: AccessControl
          url: https://nsis.sourceforge.net/mediawiki/images/4/4a/AccessControl.zip

      - name: Install `NsArray` from web
        uses: negrutiu/nsis-install-plugin@v1
        with:
          plugin-name: NsArray
          url: https://nsis.sourceforge.io/mediawiki/images/9/97/NsArray.zip

      - name: Install `nsisFile` from web
        uses: negrutiu/nsis-install-plugin@v1
        with:
          plugin-name: nsisFile
          url: http://wiz0u.free.fr/prog/nsisFile/latest.php

      - name: Install `Advanced Uninstall Log` nsis header from web
        run: |
          Invoke-WebRequest -Uri "https://nsis.sourceforge.io/mediawiki/images/1/12/Advunlog.zip" -OutFile "$env:RUNNER_TEMP\Advunlog.zip"
          Expand-Archive -Path "$env:RUNNER_TEMP\Advunlog.zip" -DestinationPath "$env:RUNNER_TEMP\Advunlog" -Force
          Copy-Item -Path "$env:RUNNER_TEMP\Advunlog\Include\AdvUninstLog.nsh" -Destination "${{ steps.nsis.outputs.instdir }}\Include" -Force

      - name: Build installer
        run: makensis RS3DInstaller.nsi
      
      - name: Upload artifact
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: RS3DInstaller # Unique identifier for the artifact
          path: "RS3DInstaller-${{ github.ref }}.exe"

  release:
    runs-on: windows-latest
    if: github.ref_type == 'tag'
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: RS3DInstaller # Must match the upload name

      - name: Upload installer artifact
        uses: softprops/action-gh-release@v3
        with:
          files: "RS3DInstaller-${{ github.ref }}.exe"
